layout lecture1-2
js-tasks-ru/htmlcss-20210409_ivan-lobanov pull request #3
Opened 2021-04-20 22:12 UTC by arkhemlol

решение для 1,2 лекции для разметки не по задачнику
вопрос по ширине для карточек - не работает для 350px, почему?

2021-04-20 22:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-24 11:28 UTC, GSemikozov requested changes

2021-04-24 11:28 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta charset="utf-8" />
ого, у нас не xhtml, советую отключить автозакрытие тэгов :)

2021-04-24 11:28 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta charset="utf-8" />
или - это автоформатирование через наш встроенный prettier?
если да, но настройки поменяю я.

2021-04-24 11:28 UTC, GSemikozov commented on assets/css/main.css
> +  --white: 255, 255, 255;
возможно легче было бы сразу обернуть в rgb() ?  чтобы не делать это каждый раз везде где используем эти переменные + будет неочевидно что цвет задан именно так, и мы можем когда-нибудь забыть об этом и написать так - color: (var--primary) :)

2021-04-24 11:28 UTC, GSemikozov commented on components/nav/nav.css
> +.nav__item-active {
если это модификатор, советую записать так: `.nav__item_active`

2021-04-24 11:28 UTC, GSemikozov commented on components/preview/preview.css
> +  height: 1036px;
пожалуй, поскольку мы уже добавляем карточки - можно удалить это свойство

2021-04-24 11:28 UTC, GSemikozov commented on components/preview/preview.css
> +  /* почему не работает 350px? */
потому что ширина контейнера определена немного неточно :)
```
.page__box {
  max-width: 1100px;
  }
  ```
  а должно быть:
  ```
.page__box {
  max-width: 1110px;
  }
  ```

2021-04-26 12:40 UTC, arkhemlol commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta charset="utf-8" />
да, через prettier

2021-04-26 12:40 UTC, arkhemlol commented on components/nav/nav.css
> +.nav__item-active {
я везде модификаторы писал через `-`. Согласен, что нижнее подчеркивание лучше. Поменяю везде.

2021-04-26 12:41 UTC, arkhemlol commented on components/preview/preview.css
> +  /* почему не работает 350px? */
:)

2021-04-26 12:53 UTC, arkhemlol commented on assets/css/main.css
> +  --white: 255, 255, 255;
Если они будут все обурнуты в `rgb()`, то как потом делать вот такое:

```
.color-accent {
  background: rgba(var(--primary), 0.5)
}
```
вот так у меня не заработало...

2021-04-26 19:53 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta charset="utf-8" />
ок, это поправлю с нашей стороны

2021-04-26 19:53 UTC, GSemikozov commented on assets/css/main.css
> +  --white: 255, 255, 255;
в личной беседе обсудили*

2021-04-26 19:54 UTC, GSemikozov approved these changes

2021-04-26 19:54 UTC, merged